export const getAllProjects = "/v1/project";
export const getAllProjectsById = "/v1/project"; // pass id
export const getAllCountry = "/v1/country";
export const saveProject = "/v1/project";
export const getProjectById = "/v1/project"; // pass id
export const getCompanyData = "/v1/company";
export const getStates = "/v1/State";
export const getCities = "/v1/City";
export const getAllProjectLocation = "/v1/ProjectLocation";
export const getAllProjectLocationById = "/v1/ProjectLocation"; // pass id
export const getAllDesignation = "/v1/Designation";
export const getAllDesignationById = "/v1/Designation"; // pass id
export const getAllDepartment = "/v1/Department";
export const getAllDepartmentById = "/v1/Department"; // pass id
export const getAllApprovalGroup = "/v1/ApprovalGroup";
export const getAllRoles = "/v1/Roles";
export const getAllSettings = "/v1/Setting";
export const getAllSettingsById = "/v1/Setting"; // pass id
export const getAllItemMaster = "/v1/ItemMaster";
export const getAllItemMasterById = "/v1/ItemMaster"; // pass id
export const getAllTemplate = "/v1/Template";
export const getAllTemplateById = "/v1/Template"; // pass id
