export const BankMasterData = [
  {
    BankName: "Test Bank",
    IsActive: true,
    ID: 1,
    Address: "123 Test St",
    Branch: "Test Branch",
    IFSC: "TEST1234",
    SWIFT: "TEST1234",
  },
  {
    BankName: "Sample Bank",
    IsActive: false,
    ID: 2,
    Address: "456 Sample St",
    Branch: "Sample Branch",
    IFSC: "SAMPLE1234",
    SWIFT: "SAMPLE1234",
  },
  {
    BankName: "Sample Bank",
    IsActive: true,
    ID: 3,
    Address: "789 Sample St",
    Branch: "Sample Branch",
    IFSC: "SAMPLE1234",
    SWIFT: "SAMPLE1234",
  },
  {
    BankName: "Sample Bank",
    IsActive: true,
    ID: 4,
    Address: "101 Sample St",
    Branch: "Sample Branch",
    IFSC: "SAMPLE1234",
    SWIFT: "SAMPLE1234",
  },
  {
    BankName: "Sample Bank",
    IsActive: false,
    ID: 5,
    Address: "202 Sample St",
    Branch: "Sample Branch",
    IFSC: "SAMPLE1234",
    SWIFT: "SAMPLE1234",
  },
  {
    BankName: "Sample Bank",
    IsActive: true,
    ID: 6,
    Address: "303 Sample St",
    Branch: "Sample Branch",
    IFSC: "SAMPLE1234",
    SWIFT: "SAMPLE1234",
  },
];
