export const DepartmentListFake = [
  {
    name: "HR",
    color: "#9FB3DF",
    employees: [
      {
        id: "1",
        name: "Aarti Sharma",
        dept: "HR",
        empcode: "HR001",
        ismandatory: false,
      },
      {
        id: "2",
        name: "Ravi Kumar",
        dept: "HR",
        empcode: "HR002",
        ismandatory: false,
      },
      {
        id: "3",
        name: "Neha Verma",
        dept: "HR",
        empcode: "HR003",
        ismandatory: false,
      },
      {
        id: "4",
        name: "Manoj Gupta",
        dept: "HR",
        empcode: "HR004",
        ismandatory: false,
      },
      {
        id: "5",
        name: "Pooja Jain",
        dept: "HR",
        empcode: "HR005",
        ismandatory: false,
      },
      {
        id: "6",
        name: "Suresh Rathi",
        dept: "HR",
        empcode: "HR006",
        ismandatory: false,
      },
      {
        id: "7",
        name: "Divya Chauhan",
        dept: "HR",
        empcode: "HR007",
        ismandatory: false,
      },
      {
        id: "8",
        name: "Alok Mishra",
        dept: "HR",
        empcode: "HR008",
        ismandatory: false,
      },
      {
        id: "9",
        name: "Sneha Kapoor",
        dept: "HR",
        empcode: "HR009",
        ismandatory: false,
      },
      {
        id: "10",
        name: "Varun Yadav",
        dept: "HR",
        empcode: "HR010",
        ismandatory: false,
      },
    ],
  },
  {
    name: "Finance",
    color: "#FED16A",
    employees: [
      {
        id: "11",
        name: "Anil Mehta",
        dept: "Finance",
        empcode: "FIN001",
        ismandatory: false,
      },
      {
        id: "12",
        name: "Priya Iyer",
        dept: "Finance",
        empcode: "FIN002",
        ismandatory: false,
      },
      {
        id: "13",
        name: "Sanjay Bansal",
        dept: "Finance",
        empcode: "FIN003",
        ismandatory: false,
      },
      {
        id: "14",
        name: "Ritika Khanna",
        dept: "Finance",
        empcode: "FIN004",
        ismandatory: false,
      },
      {
        id: "15",
        name: "Mohit Tiwari",
        dept: "Finance",
        empcode: "FIN005",
        ismandatory: false,
      },
      {
        id: "16",
        name: "Kavita Rani",
        dept: "Finance",
        empcode: "FIN006",
        ismandatory: false,
      },
      {
        id: "17",
        name: "Deepak Sharma",
        dept: "Finance",
        empcode: "FIN007",
        ismandatory: false,
      },
      {
        id: "18",
        name: "Simran Ahuja",
        dept: "Finance",
        empcode: "FIN008",
        ismandatory: false,
      },
      {
        id: "19",
        name: "Harsh Vardhan",
        dept: "Finance",
        empcode: "FIN009",
        ismandatory: false,
      },
      {
        id: "20",
        name: "Anuja Ghosh",
        dept: "Finance",
        empcode: "FIN010",
        ismandatory: false,
      },
    ],
  },
  {
    name: "Admin",
    color: "#AEC8A4",
    employees: [
      {
        id: "21",
        name: "Sunita Desai",
        dept: "Admin",
        empcode: "ADM001",
        ismandatory: false,
      },
      {
        id: "22",
        name: "Vikram Singh",
        dept: "Admin",
        empcode: "ADM002",
        ismandatory: false,
      },
      {
        id: "23",
        name: "Rohit Shetty",
        dept: "Admin",
        empcode: "ADM003",
        ismandatory: false,
      },
      {
        id: "24",
        name: "Pallavi Bhatt",
        dept: "Admin",
        empcode: "ADM004",
        ismandatory: false,
      },
      {
        id: "25",
        name: "Amitabh Dubey",
        dept: "Admin",
        empcode: "ADM005",
        ismandatory: false,
      },
      {
        id: "26",
        name: "Gauri Joshi",
        dept: "Admin",
        empcode: "ADM006",
        ismandatory: false,
      },
      {
        id: "27",
        name: "Nitin Raj",
        dept: "Admin",
        empcode: "ADM007",
        ismandatory: false,
      },
      {
        id: "28",
        name: "Isha Talwar",
        dept: "Admin",
        empcode: "ADM008",
        ismandatory: false,
      },
      {
        id: "29",
        name: "Rajesh Bhalla",
        dept: "Admin",
        empcode: "ADM009",
        ismandatory: false,
      },
      {
        id: "30",
        name: "Shruti Menon",
        dept: "Admin",
        empcode: "ADM010",
        ismandatory: false,
      },
    ],
  },
  {
    name: "IT",
    color: "#FFDCDC",
    employees: [
      {
        id: "31",
        name: "Karan Patel",
        dept: "IT",
        empcode: "IT001",
        ismandatory: false,
      },
      {
        id: "32",
        name: "Meena Joshi",
        dept: "IT",
        empcode: "IT002",
        ismandatory: false,
      },
      {
        id: "33",
        name: "Ashwin Rao",
        dept: "IT",
        empcode: "IT003",
        ismandatory: false,
      },
      {
        id: "34",
        name: "Radhika Nair",
        dept: "IT",
        empcode: "IT004",
        ismandatory: false,
      },
      {
        id: "35",
        name: "Naveen Chawla",
        dept: "IT",
        empcode: "IT005",
        ismandatory: false,
      },
      {
        id: "36",
        name: "Tanya Mehta",
        dept: "IT",
        empcode: "IT006",
        ismandatory: false,
      },
      {
        id: "37",
        name: "Siddharth Jain",
        dept: "IT",
        empcode: "IT007",
        ismandatory: false,
      },
      {
        id: "38",
        name: "Komal Deshpande",
        dept: "IT",
        empcode: "IT008",
        ismandatory: false,
      },
      {
        id: "39",
        name: "Ankur Sehgal",
        dept: "IT",
        empcode: "IT009",
        ismandatory: false,
      },
      {
        id: "40",
        name: "Bhavna Reddy",
        dept: "IT",
        empcode: "IT010",
        ismandatory: false,
      },
    ],
  },
  {
    name: "Marketing",
    color: "#F2C078",
    employees: [
      {
        id: "41",
        name: "Rahul Nair",
        dept: "Marketing",
        empcode: "MKT001",
        ismandatory: false,
      },
      {
        id: "42",
        name: "Swati Rao",
        dept: "Marketing",
        empcode: "MKT002",
        ismandatory: false,
      },
      {
        id: "43",
        name: "Tarun Malhotra",
        dept: "Marketing",
        empcode: "MKT003",
        ismandatory: false,
      },
      {
        id: "44",
        name: "Anjali Pandey",
        dept: "Marketing",
        empcode: "MKT004",
        ismandatory: false,
      },
      {
        id: "45",
        name: "Vishal Bhatia",
        dept: "Marketing",
        empcode: "MKT005",
        ismandatory: false,
      },
      {
        id: "46",
        name: "Sneha Ramesh",
        dept: "Marketing",
        empcode: "MKT006",
        ismandatory: false,
      },
      {
        id: "47",
        name: "Kunal Dey",
        dept: "Marketing",
        empcode: "MKT007",
        ismandatory: false,
      },
      {
        id: "48",
        name: "Priti Shah",
        dept: "Marketing",
        empcode: "MKT008",
        ismandatory: false,
      },
      {
        id: "49",
        name: "Ajay Kapoor",
        dept: "Marketing",
        empcode: "MKT009",
        ismandatory: false,
      },
      {
        id: "50",
        name: "Nisha Pillai",
        dept: "Marketing",
        empcode: "MKT010",
        ismandatory: false,
      },
    ],
  },
];
