const activeMenus = [
  "Project",
  "Dashboard",
  "Company",
  "EmployeeMaster",
  "Country",
  "City",
  "State",
  "ProjectLocation",
  "unitOfMeasurement",
  "ApprovalMatrix",
  "Designation",
  "Department",
  "wip",
  "ApprovalGroup",
  "role",
  "userManagement",
  "menu",
  "menuGroup",
  "formMaster",
  "template",
  "settingMaster",
  "formAttribute",
  "formAttributeDetail",
  "itemMaster",
  "Client",
  "ApprovalCategory",
  "ApprovalReason",
  "CustomerGroup",
  "CustomerMaster",
  "ModeOfPayment",
  "BankMaster",
  "Divison",
  "ApprovalMatrixUI",
];

export default activeMenus;
