export const CustomerMasterData = [
  {
    Name: "Acme Corp",
    Alias: "ACME",
    GroupName: "Retail",
    City: "Mumbai",
    State: "Maharashtra",
    Country: "India",
    Pincode: "400001",
    Address: "123 Fort Road, Mumbai",
    GstInRegistered: true,
    GstNo: "27ABCDE1234F1Z5",
    PanNumber: "ABCDE1234F",
    ContactPersonName: "Rajesh Kumar",
    MobileNo: "9876543210",
    Email: "rajesh@acmecorp.com",
    IsActive: true,
  },
  {
    Name: "Bright Solutions",
    Alias: "Bright",
    GroupName: "IT Services",
    City: "Bangalore",
    State: "Karnataka",
    Country: "India",
    Pincode: "560001",
    Address: "45 MG Road, Bangalore",
    GstInRegistered: false,
    GstNo: "",
    PanNumber: "FGHIJ5678K",
    ContactPersonName: "Anjali Mehra",
    MobileNo: "9123456789",
    Email: "anjali@brightsolutions.in",
    IsActive: true,
  },
  {
    Name: "Oceanic Exports",
    Alias: "Oceanic",
    GroupName: "Exports",
    City: "Chennai",
    State: "Tamil Nadu",
    Country: "India",
    Pincode: "600001",
    Address: "89 Marina Beach Road, Chennai",
    GstInRegistered: true,
    GstNo: "33JKLMN9012P3Z2",
    PanNumber: "JKLMN9012P",
    ContactPersonName: "Sundar Raman",
    MobileNo: "9812345678",
    Email: "sundar@oceanicexports.com",
    IsActive: true,
  },
  {
    Name: "TechNova Labs",
    Alias: "TechNova",
    GroupName: "Research",
    City: "Hyderabad",
    State: "Telangana",
    Country: "India",
    Pincode: "500001",
    Address: "67 Hitech City, Hyderabad",
    GstInRegistered: false,
    GstNo: "",
    PanNumber: "QRSTU3456V",
    ContactPersonName: "Neha Reddy",
    MobileNo: "9098765432",
    Email: "neha@technova.io",
    IsActive: true,
  },
  {
    Name: "GreenMart",
    Alias: "GMart",
    GroupName: "E-Commerce",
    City: "Pune",
    State: "Maharashtra",
    Country: "India",
    Pincode: "411001",
    Address: "201 JM Road, Pune",
    GstInRegistered: true,
    GstNo: "27WXYZA7890B2Z8",
    PanNumber: "WXYZA7890B",
    ContactPersonName: "Amit Patil",
    MobileNo: "9876012345",
    Email: "amit@greenmart.in",
    IsActive: true,
  },
];
